# Generated by Django 2.2.14 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='state_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
